export const GET_WEATHER ="GET_WEATHER";
export const GET_LOCATION ="GET_LOCATION";
export const GET_WEATHER_ERROR = "GET_WEATHER_ERROR";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";
export const START_WEATHER_FETCH = "START_WEATHER_FETCH";
export const CHANGE_TEMP_UNIT = "CHANGE_TEMP_UNIT";
export const CHANGE_APP_THEME = "CHANGE_APP_THEME";